### ISSUE TITLE
How are methods meant to be used?

### ISSUE THREAD

**Issue by tihomir-kit** [SomusHQ/vue-friendly-captcha#19]
Hi, 

How are the "methods" mean to be used? Is there a global config object that's supposed to be passed to `<VueFriendlyCaptcha /> or something else?

For example if I want to reset the captcha, how do I do it? Sorry to bother you, but it's not really clear how to do that from README.

Thanks!

**Comment by jozsefsallai** [comment]
Hello. You can pass a ref to the element and then access methods through that ref.

For Vue 2:

```vue
<template>
  <vue-friendly-captcha sitekey="your-site-key" ref="captcha" />
</template>

<script>
  // ...
  this.$refs.captcha.reset();
</script>
```

https://v2.vuejs.org/v2/api/#ref

For Vue 3:

```vue
<template>
  <vue-friendly-captcha sitekey="your-site-key" ref="captcha" />
</template>

<script>
  import { ref } from 'vue';

  const captcha = ref(null);

  // ...

  captcha.value?.reset();
</script>
```

https://vuejs.org/guide/essentials/template-refs.html#ref-on-component

**Comment by tihomir-kit** [comment]
Aaah, right, ok. Thanks!
